services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    ports:
      - "${PORT:-80}:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=webhook_integration_app_production
    restart: unless-stopped

volumes:
  postgres_data:
