default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default
  workers:
    - queues: [default, webhooks, integrations]
      threads: 3
      polling_interval: 2

test:
  <<: *default

production:
  <<: *default
  workers:
    - queues: [default, webhooks, integrations, critical]
      threads: 5
      polling_interval: 0.1
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 3) %>
